### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by r57zone** [metallicent/psvr#1]
Hello, could you add some features to your player?

1. New minimalist interface maybe like this:
![](https://user-images.githubusercontent.com/9499881/31562711-7d593254-b06d-11e7-9db6-8f1b53e79e25.jpg)

2. Support [TrueOpenVR](https://github.com/TrueOpenVR) vr standard (open source vr standard) for Windows version. [Sample](https://github.com/TrueOpenVR/TrueOpenVR-Samples/blob/master/%D0%A1%2B%2B/GetData/GetData/GetData.cpp) for get data (yaw, pitch, roll) with API.  It is also necessary to run the video window ("PSVR HMD") on screen (HKEY_CURRENT_USER\Software\TrueOpenVR parameter "ScreenIndex", [docs](https://github.com/TrueOpenVR/TrueOpenVR-Core/tree/master/Docs)), whose index can be obtained in the Windows registry.

3. Hotkeys to play - pause (space), stop, and move (CTRL + Left or CTRL + Right to fast and Left or Right to slow change position).

4. Would also like to be able to stop, rewind and play inside VR, for example, by pointing the head down and selecting items with head tracking.
![unnamed](https://user-images.githubusercontent.com/9499881/31563192-20edb0ec-b06f-11e7-8954-86f616077e30.png)

Thanks.

**Comment by thestr4ng3r** [comment]
I am kind of sceptical about the sense of TrueOpenVR with OpenXR coming soon.

About the other things, I am currently very busy with other projects, so I probably won't have the time to work on the player any time soon. However, I would be happy to receive pull requests ;-)

**Comment by r57zone** [comment]
OpenXR seems likely not to become popular because output is planned only for next summer.

TrueOpenVR is already written and it is convenient, as it is not tied to Steam or Oculus Home. Works with various DIY VR devices. For example, Arduino tracker and Android smartphone or HDMI display.
